on: push

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest

    name: Jira Login
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Jira TODO
      uses: atlassian/gajira-todo@v3
      with:
        project: PAR # PAR Project name from JIRA!
        issuetype: Task
        description: Created automatically via GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Find in commit messages
      uses: atlassian/gajira-find-issue-key@v3
      with:
        from: commits    

    - name: Check Issue
      shell: bash
      run: |
        if [[ "${{steps.find_issue.outputs.ISSUE_ID}}" == "" ]]; then
          echo "Please name your branch according to the JIRA issue: [project_key]-[task_number]-branch_name"
          exit 1
        fi
        echo succcessfully found JIRA issue: ${{steps.find_issue.outputs.ISSUE_ID}}

    - name: Transition issue
      if: ${{ success() }}
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.find_issue.outputs.ISSUE_ID }}
        transition: "Code review"
# add few changes to take GA workflow